import PDFDocument from 'pdfkit';
import { marked } from 'marked';

/**
 * Core function to generate PDF from structured data using PDFKit
 * This replaces Puppeteer/Chromium to avoid serverless compatibility issues
 */
export async function generatePdfBuffer(buildContent: (doc: typeof PDFDocument.prototype) => void): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 60, bottom: 60, left: 60, right: 60 },
                bufferPages: true,
                autoFirstPage: false // Explicitly control first page
            });

            const buffers: Buffer[] = [];

            doc.on('data', (buffer) => buffers.push(buffer));
            doc.on('end', () => resolve(Buffer.concat(buffers)));
            doc.on('error', (err) => reject(err));

            // Execute the content builder
            buildContent(doc);

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

/**
 * Generates the official Compliance Report PDF
 * Following LexOculus editorial design: serif headers, monospace data, clean borders
 */
export async function generateComplianceReport(data: any): Promise<Buffer> {
    return generatePdfBuffer((doc) => {
        const PRIMARY = '#000000';
        const ACCENT = '#FF4F00';
        const GRAY = '#555555';
        const LIGHT_GRAY = '#999999';
        const BORDER = '#E5E5E5';

        // Helper: Draw Header & Divider
        const drawHeader = (docLevel: typeof doc, sectionTitle?: string) => {
            docLevel.fontSize(20)
                .font('Times-Bold')
                .fillColor(PRIMARY)
                .text('LEX', 60, 60, { continued: true })
                .fillColor(ACCENT)
                .text('OCULUS');

            docLevel.fontSize(8)
                .font('Courier')
                .fillColor(GRAY)
                .text(`GENERATED: ${new Date().toLocaleDateString('en-US').toUpperCase()}`, 400, 60, { align: 'right' });

            docLevel.fontSize(8)
                .text(`REPOSITORY: ${(data.repo?.repo_name || 'N/A').toUpperCase()}`, 400, 72, { align: 'right' });

            if (sectionTitle) {
                docLevel.text(`SECTION: ${sectionTitle.toUpperCase()}`, 400, 84, { align: 'right' });
            }

            docLevel.moveTo(60, 100)
                .lineTo(535, 100)
                .lineWidth(2)
                .stroke(PRIMARY);

            return 120; // Return current Y position
        };

        // Helper: Draw Footer
        const drawFooter = (docLevel: typeof doc, pageNum: number) => {
            const bottomY = docLevel.page.height - 50;
            docLevel.fontSize(8)
                .font('Courier')
                .fillColor(LIGHT_GRAY)
                .text('Generated by LexOculus Compliance Platform', 60, bottomY - 12, { width: 475, align: 'center' })
                .text(`CONFIDENTIAL - PAGE ${pageNum}`, 60, bottomY, { width: 475, align: 'center' });
        };

        // Helper: Add new page with header/footer
        let pageCount = 1;
        const addFormattedPage = (sectionTitle?: string) => {
            doc.addPage();
            pageCount++;
            return drawHeader(doc, sectionTitle);
        };

        // ==========================================
        // PAGE 1: COVER & EXECUTIVE SUMMARY
        // ==========================================
        let yPos = addFormattedPage('Executive Summary');

        doc.fontSize(32)
            .font('Times-Bold')
            .fillColor(PRIMARY)
            .text('Compliance Report', 60, yPos);
        yPos += 40;

        doc.fontSize(11)
            .font('Helvetica')
            .fillColor(GRAY)
            .text('Official EU AI Act Risk Assessment & Capabilities Analysis', 60, yPos, { width: 475 });
        yPos += 30;

        // Score Card
        const score = data.assessment?.final_risk_score || 0;
        const classification = data.assessment?.final_risk_classification || 'UNKNOWN';

        let riskColor = PRIMARY;
        let riskBg = '#F5F5F5';
        if (classification === 'MINIMAL_RISK') { riskColor = '#10B981'; riskBg = '#ECFDF5'; }
        else if (classification === 'LIMITED_RISK') { riskColor = '#F59E0B'; riskBg = '#FFFBEB'; }
        else if (classification === 'HIGH_RISK') { riskColor = ACCENT; riskBg = '#FFF7ED'; }
        else if (classification === 'UNACCEPTABLE') { riskColor = '#EF4444'; riskBg = '#FEF2F2'; }

        doc.rect(60, yPos, 475, 140)
            .fillAndStroke(riskBg, PRIMARY)
            .lineWidth(2);

        doc.fontSize(9).font('Courier-Bold').fillColor(LIGHT_GRAY)
            .text('FINAL COMPLIANCE SCORE', 60, yPos + 20, { width: 475, align: 'center' });

        doc.fontSize(56).font('Times-Bold').fillColor(PRIMARY)
            .text(`${score}`, 60, yPos + 45, { width: 475, align: 'center' });

        doc.fontSize(16).font('Helvetica').fillColor(GRAY)
            .text('/100', 60, yPos + 105, { width: 475, align: 'center' });

        doc.fontSize(12).font('Courier-Bold').fillColor(riskColor)
            .text(classification.replace(/_/g, ' '), 60, yPos + 123, { width: 475, align: 'center' });

        yPos += 170;

        // Executive Narrative
        doc.fontSize(16).font('Times-Bold').fillColor(PRIMARY).text('Executive Narrative', 60, yPos);
        yPos += 25;
        doc.moveTo(60, yPos).lineTo(535, yPos).lineWidth(1).stroke(BORDER);
        yPos += 15;

        const narrative = data.assessment?.final_narrative || 'No executive narrative provided for this assessment.';
        doc.fontSize(11).font('Helvetica').fillColor(PRIMARY)
            .text(narrative, 60, yPos, { width: 475, align: 'justify', lineGap: 4 });

        yPos = doc.y + 40;

        // ==========================================
        // PAGE 2: SYSTEM OVERVIEW
        // ==========================================
        yPos = addFormattedPage('System Overview');

        doc.fontSize(18).font('Times-Bold').fillColor(PRIMARY).text('System Operations & Context', 60, yPos);
        yPos += 25;
        doc.moveTo(60, yPos).lineTo(535, yPos).lineWidth(1).stroke(BORDER);
        yPos += 15;

        const context = data.assessment?.context_summary || {};
        const contextItems = [
            { label: 'Intended Use', value: context.intended_use || 'Not Specified' },
            { label: 'Target Users', value: context.target_users || 'Not Specified' },
            { label: 'Deployment Region', value: context.deployment_region || 'Not Specified' },
            { label: 'Human Oversight', value: context.has_human_oversight ? 'Implemented' : 'Not Implemented' },
            { label: 'Testing Procedure', value: context.has_testing_procedure ? 'Established' : 'Not Established' },
            { label: 'Data Safeguards', value: context.has_data_safeguards ? 'Active' : 'Missing' },
            { label: 'Appeal Mechanism', value: context.has_appeal_mechanism ? 'Available' : 'Unavailable' },
            { label: 'Transparency Statement', value: context.has_transparency_statement ? 'Published' : 'Not Published' }
        ];

        contextItems.forEach(item => {
            if (yPos > 700) { yPos = addFormattedPage('System Overview'); }

            doc.fontSize(10).font('Courier-Bold').fillColor(GRAY).text(item.label.toUpperCase(), 60, yPos, { width: 150 });
            doc.fontSize(11).font('Helvetica').fillColor(PRIMARY).text(item.value, 220, yPos, { width: 315 });
            yPos = doc.y + 15;
            doc.moveTo(60, yPos).lineTo(535, yPos).lineWidth(0.5).stroke(BORDER);
            yPos += 15;
        });

        // ==========================================
        // PAGE 3: CAPABILITIES & RISK BREAKDOWN
        // ==========================================
        yPos = addFormattedPage('Risk Breakdown');

        doc.fontSize(18).font('Times-Bold').fillColor(PRIMARY).text('Detected Capabilities', 60, yPos);
        yPos += 25;
        doc.moveTo(60, yPos).lineTo(535, yPos).lineWidth(1).stroke(BORDER);
        yPos += 15;

        const capabilities = data.capabilities?.capabilities || data.capabilities?.detected_capabilities || [];
        if (capabilities.length === 0) {
            doc.fontSize(11).font('Helvetica').fillColor(GRAY).text('No specific AI capabilities detected during static analysis.', 60, yPos);
            yPos += 30;
        } else {
            capabilities.forEach((cap: string) => {
                if (yPos > 700) { yPos = addFormattedPage('Risk Breakdown'); }
                doc.fontSize(11).font('Helvetica').fillColor(PRIMARY)
                    .text('■', 70, yPos).text(cap, 90, yPos, { width: 445 });
                yPos = doc.y + 10;
            });
            yPos += 20;
        }

        // ==========================================
        // PAGE 4: EVIDENCE & VERIFICATION
        // ==========================================
        yPos = addFormattedPage('Evidence & Verification');

        doc.fontSize(18).font('Times-Bold').fillColor(PRIMARY).text('Verification Evidence Repository', 60, yPos);
        yPos += 25;
        doc.moveTo(60, yPos).lineTo(535, yPos).lineWidth(1).stroke(BORDER);
        yPos += 15;

        const evidence = data.assessment?.evidence_items || [];
        if (evidence.length === 0) {
            doc.fontSize(11).font('Helvetica').fillColor(GRAY).text('No structured evidence items recorded for this assessment.', 60, yPos);
        } else {
            evidence.forEach((item: any) => {
                if (yPos > 650) { yPos = addFormattedPage('Evidence & Verification'); }

                doc.rect(60, yPos, 475, 5).fill(PRIMARY);
                yPos += 15;

                doc.fontSize(12).font('Times-Bold').fillColor(PRIMARY).text(item.category, 60, yPos);
                yPos += 20;

                doc.fontSize(10).font('Helvetica-Oblique').fillColor(GRAY).text(`Reference: ${item.regulatory_reference || 'N/A'}`, 60, yPos);
                yPos += 15;

                doc.fontSize(11).font('Helvetica').fillColor(PRIMARY).text(item.description, 60, yPos, { width: 475, align: 'justify' });
                yPos = doc.y + 10;

                doc.fontSize(9).font('Courier-Bold').fillColor(LIGHT_GRAY).text(`IMPACT: ${item.supports_classification} | CONFIDENCE: ${item.confidence}`, 60, yPos);
                yPos += 25;
            });
        }

        // ==========================================
        // PAGE 5: COMPLIANCE ROADMAP
        // ==========================================
        yPos = addFormattedPage('Compliance Roadmap');

        doc.fontSize(18).font('Times-Bold').fillColor(PRIMARY).text('Readiness & Action Items', 60, yPos);
        yPos += 25;
        doc.moveTo(60, yPos).lineTo(535, yPos).lineWidth(1).stroke(BORDER);
        yPos += 15;

        const readiness = data.assessment?.compliance_readiness || {};

        doc.fontSize(14).font('Times-Bold').fillColor(PRIMARY).text('Overall Readiness Status', 60, yPos);
        yPos += 20;
        doc.fontSize(11).font('Helvetica').fillColor(GRAY).text(readiness.overall_readiness || 'Pending review.', 60, yPos, { width: 475 });
        yPos = doc.y + 30;

        // Action Items
        doc.fontSize(14).font('Times-Bold').fillColor(PRIMARY).text('Required Developer Actions', 60, yPos);
        yPos += 20;

        const actions = readiness.developer_action_items || [];
        if (actions.length === 0) {
            doc.fontSize(11).font('Helvetica').fillColor(PRIMARY).text('No immediate actions required.', 60, yPos);
            yPos += 30;
        } else {
            actions.forEach((action: string) => {
                if (yPos > 700) { yPos = addFormattedPage('Compliance Roadmap'); }
                doc.fontSize(11).font('Helvetica').fillColor(PRIMARY)
                    .text('→', 70, yPos).text(action, 90, yPos, { width: 445 });
                yPos = doc.y + 10;
            });
            yPos += 20;
        }

        // ==========================================
        // PAGE 6: CERTIFICATE DECLARATION
        // ==========================================
        yPos = addFormattedPage('Declaration of Assessment');

        doc.rect(60, yPos, 475, 400).lineWidth(3).stroke(PRIMARY);
        doc.rect(70, yPos + 10, 455, 380).lineWidth(1).stroke(PRIMARY);

        yPos += 40;
        doc.fontSize(24).font('Times-Bold').fillColor(PRIMARY).text('Declaration of Verification', 60, yPos, { width: 475, align: 'center' });
        yPos += 30;

        doc.fontSize(11).font('Helvetica').fillColor(GRAY).text(
            'This document certifies that the repository identified below has been subjected to static code analysis and contextual operational verification in accordance with the frameworks established by the EU Artificial Intelligence Act.',
            100, yPos, { width: 395, align: 'center' }
        );
        yPos += 80;

        doc.fontSize(14).font('Courier-Bold').fillColor(PRIMARY).text(`TARGET: ${(data.repo?.repo_name || 'UNKNOWN').toUpperCase()}`, 60, yPos, { width: 475, align: 'center' });
        yPos += 20;
        doc.fontSize(14).font('Courier-Bold').fillColor(PRIMARY).text(`OWNER: ${(data.repo?.repo_owner || 'UNKNOWN').toUpperCase()}`, 60, yPos, { width: 475, align: 'center' });
        yPos += 40;

        doc.fontSize(16).font('Courier-Bold').fillColor(riskColor).text(`FINAL ASSESSMENT: ${classification.replace(/_/g, ' ')}`, 60, yPos, { width: 475, align: 'center' });
        yPos += 80;

        doc.moveTo(150, yPos).lineTo(445, yPos).lineWidth(1).stroke(PRIMARY);
        yPos += 10;
        doc.fontSize(10).font('Helvetica-Oblique').fillColor(GRAY).text('Digitally Verified & Signed by LexOculus System', 60, yPos, { width: 475, align: 'center' });

        // Add Footers to all pages retroactively
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i);
            drawFooter(doc, i + 1);
        }
    });
}

/**
 * Generates the Trust Pack PDF for vendors
 * Editorial certificate design
 */
export async function generateTrustPackPDF(data: any): Promise<Buffer> {
    return generatePdfBuffer((doc) => {
        const PRIMARY = '#000000';
        const ACCENT = '#FF4F00';
        const GRAY = '#555555';

        // Add first page explicitly
        doc.addPage();

        // === HEADER ===
        doc.fontSize(20)
            .font('Times-Bold')
            .fillColor(PRIMARY)
            .text('LEX', 60, 60, { continued: true })
            .fillColor(ACCENT)
            .text('OCULUS');

        // === CERTIFICATE SEAL ===
        // Outer border (thick)
        doc.rect(120, 200, 350, 320)
            .lineWidth(3)
            .stroke(PRIMARY);

        // Inner border
        doc.rect(130, 210, 330, 300)
            .lineWidth(1)
            .stroke(PRIMARY);

        // Title
        doc.fontSize(32)
            .font('Times-Bold')
            .fillColor(PRIMARY)
            .text('Scan Verified', 120, 250, { width: 350, align: 'center' });

        // Subtitle
        doc.fontSize(12)
            .font('Helvetica')
            .fillColor(GRAY)
            .text('This software repository has been scanned', 120, 300, { width: 350, align: 'center' })
            .text('for EU AI Act compliance risks.', 120, 317, { width: 350, align: 'center' });

        // Risk badge
        const riskText = data.riskClassification || 'UNKNOWN';
        let riskColor = PRIMARY;
        if (riskText.includes('MINIMAL')) riskColor = '#10B981';
        else if (riskText.includes('LIMITED')) riskColor = '#F59E0B';
        else if (riskText.includes('HIGH')) riskColor = ACCENT;
        else if (riskText.includes('UNACCEPTABLE')) riskColor = '#EF4444';

        doc.fontSize(16)
            .font('Courier-Bold')
            .fillColor(riskColor)
            .text(`RISK LEVEL: ${riskText.replace(/_/g, ' ')}`, 120, 360, { width: 350, align: 'center' });

        // Metadata
        doc.fontSize(9)
            .font('Courier')
            .fillColor(GRAY)
            .text(`REPOSITORY: ${(data.repoScan?.repo_name || 'N/A').toUpperCase()}`, 120, 420, { width: 350, align: 'center' })
            .text(`SCAN DATE: ${new Date(data.generatedAt).toLocaleDateString('en-US').toUpperCase()}`, 120, 435, { width: 350, align: 'center' })
            .text(`REFERENCE ID: ${(data.repoScan?.id?.slice(0, 8) || 'N/A').toUpperCase()}`, 120, 450, { width: 350, align: 'center' });

        // Footer (Last Page Only)
        const bottomY = doc.page.height - 60;

        doc.fontSize(8)
            .font('Courier')
            .fillColor(GRAY)
            .text('Generated by LexOculus EU AI Act Compliance Platform', 60, bottomY - 12, { width: 475, align: 'center' })
            .text(new Date().toISOString(), 60, bottomY, { width: 475, align: 'center' });
    });
}

/**
 * Generates a compliance document PDF from Markdown content
 * Renders Markdown structure directly to PDFKit for precise layout control
 */
export async function generateDocumentPDF(documentData: {
    title: string;
    documentType: string;
    aiSystemName: string;
    markdown: string;
}): Promise<Buffer> {
    return generatePdfBuffer((doc) => {
        const PRIMARY = '#000000';
        const ACCENT = '#FF4F00';
        const GRAY = '#555555';
        const LIGHT_GRAY = '#999999';
        const BORDER = '#E5E5E5';

        // Add first page explicitly
        doc.addPage();

        // Metadata on Page 1
        // Logo
        doc.fontSize(20)
            .font('Times-Bold')
            .fillColor(PRIMARY)
            .text('LEX', 60, 60, { continued: true })
            .fillColor(ACCENT)
            .text('OCULUS');

        // Top Line
        doc.moveTo(60, 85)
            .lineTo(535, 85)
            .lineWidth(2)
            .stroke(PRIMARY);

        doc.fontSize(8)
            .font('Courier')
            .fillColor(GRAY)
            .text(`AI SYSTEM: ${documentData.aiSystemName.toUpperCase()}`, 60, 100);

        doc.fontSize(8)
            .text(`DOCUMENT TYPE: ${documentData.documentType.toUpperCase()}`, 60, 112);

        // === TITLE ===
        doc.fontSize(28)
            .font('Times-Bold')
            .fillColor(PRIMARY)
            .text(documentData.title, 60, 140, { width: 475 });

        // Move down after title
        doc.moveDown(1.5);

        // === MARKDOWN RENDERER ===
        // TRIM input to prevent trailing newlines from creating new pages
        const tokens = marked.lexer(documentData.markdown.trim());

        // USER REQUEST: Only branding on First Page.
        // We REMOVED the `doc.on('pageAdded', ...)` listener entirely.

        tokens.forEach((token, index) => {
            // Check if this is the last token to avoid trailing moveDown
            const isLast = index === tokens.length - 1;

            switch (token.type) {
                case 'heading': {
                    const level = token.depth;
                    const text = token.text;

                    doc.fillColor(PRIMARY).font('Times-Bold');

                    if (level === 1) {
                        doc.fontSize(24).text(text);
                    } else if (level === 2) {
                        doc.fontSize(18).text(text);
                        // Underline H2
                        doc.moveTo(60, doc.y + 2).lineTo(535, doc.y + 2).lineWidth(0.5).stroke(BORDER);
                    } else if (level === 3) {
                        doc.fontSize(14).text(text);
                    } else {
                        doc.fontSize(12).text(text);
                    }

                    if (!isLast) doc.moveDown(0.5);
                    doc.font('Helvetica'); // Reset font
                    break;
                }

                case 'paragraph': {
                    const text = token.text.replace(/\*\*(.*?)\*\*/g, '$1');
                    doc.fontSize(11).fillColor(PRIMARY).font('Helvetica')
                        .text(text, { width: 475, align: 'justify' });

                    if (!isLast) doc.moveDown(0.8);
                    break;
                }

                case 'list': {
                    token.items.forEach((item: any) => {
                        const text = item.text.replace(/\*\*(.*?)\*\*/g, '$1');
                        doc.fontSize(11).fillColor(PRIMARY).font('Helvetica')
                            .text('• ' + text, { indent: 20, width: 455 });
                    });

                    if (!isLast) doc.moveDown(0.8);
                    break;
                }

                case 'blockquote': {
                    const text = token.text.replace(/\*\*(.*?)\*\*/g, '$1');

                    if (!isLast) doc.moveDown(0.5);

                    // USER REQUEST: Removed orange vertical line. Just text.
                    doc.fontSize(11).font('Helvetica-Oblique').fillColor(GRAY)
                        .text(text, 75, doc.y, { width: 460, align: 'left' });

                    if (!isLast) doc.moveDown(1);
                    doc.font('Helvetica').fillColor(PRIMARY).x = 60; // Reset
                    break;
                }

                case 'hr': {
                    if (!isLast) doc.moveDown(1);
                    doc.moveTo(60, doc.y).lineTo(535, doc.y).lineWidth(0.5).stroke(BORDER);
                    if (!isLast) doc.moveDown(1);
                    break;
                }

                case 'table':
                    // Table renderer disabled (deprecated)
                    break;
            }
        });

        // === FOOTER (Last Page Only) ===
        // USER REQUEST: Just "Generated by..." and time on the last page. No page numbers.

        // Ensure we are at the bottom of the last page or add a new page if needed
        if (doc.y > 700) {
            doc.addPage();
        }

        const bottomY = doc.page.height - 60; // Bottom margin

        doc.fontSize(8).font('Courier').fillColor(LIGHT_GRAY)
            .text('Generated by LexOculus EU AI Act Compliance Platform', 60, bottomY - 12, { width: 475, align: 'center' })
            .text(new Date().toISOString(), 60, bottomY, { width: 475, align: 'center' });
    });
}
