export default function TermsPage() {
    return (
        <div className="space-y-8">
            <div>
                <h1 className="text-4xl font-black uppercase tracking-tighter mb-2">Terms of Service</h1>
                <p className="text-neutral-500 font-mono text-sm">Effective Date: April 17, 2026</p>
            </div>

            {/* Entity Information */}
            <div className="bg-neutral-50 border-2 border-black p-6 space-y-3">
                <p className="text-xs font-mono uppercase tracking-widest text-neutral-500">PARTIES</p>
                <p className="text-sm leading-relaxed">
                    This Agreement is entered into by and between:
                </p>
                <p className="text-sm leading-relaxed">
                    <strong>Varad Khoriya</strong>, an individual carrying on business under the name and style of <strong>&ldquo;LexOculus&rdquo;</strong>, a sole proprietorship established in India (hereinafter referred to as &ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;),
                </p>
                <p className="text-sm">and</p>
                <p className="text-sm leading-relaxed">
                    the user of the Services (&ldquo;User&rdquo;, &ldquo;you&rdquo;, or &ldquo;your&rdquo;).
                </p>
            </div>

            {/* Warning Box */}
            <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r">
                <div className="flex">
                    <div className="flex-shrink-0">
                        <svg className="h-5 w-5 text-amber-400" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                        </svg>
                    </div>
                    <div className="ml-3">
                        <h3 className="text-sm leading-5 font-medium text-amber-800">
                            Important Disclaimer
                        </h3>
                        <div className="mt-2 text-sm leading-5 text-amber-700">
                            <p>
                                The content, reports, risk classifications, and compliance scores generated by LexOculus are produced by <strong>automated algorithms and artificial intelligence</strong>. They are for <strong>informational and preparatory purposes only</strong> and <strong>DO NOT constitute legal advice, legal opinions, regulatory approval, or certification</strong>. You should not rely on LexOculus as a substitute for consultation with qualified legal counsel. LexOculus expressly disclaims any liability arising from reliance on its outputs.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">1. Acceptance of Terms</h2>
                <p>
                    By accessing or using the LexOculus platform ("Service") at <strong>lexoculus.com</strong>, you agree to be bound by these Terms of Service ("Terms"). If you do not agree, you may not use the Service.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">2. Description of Service</h2>
                <p>
                    LexOculus is a <strong>technical compliance auditing platform</strong> that uses automated analysis to help software developers and organizations assess their projects against the requirements of the European Union Artificial Intelligence Act (EU AI Act).
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">3. Account Registration</h2>
                <p>
                    To use the Service, you must authenticate via GitHub OAuth. You must be at least <strong>16 years of age</strong> (the minimum age for digital consent under GDPR Article 8) or have parental authorization. You are responsible for all activity under your account.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">4. Your Data Rights</h2>
                <p>
                    You retain all ownership and intellectual property rights to your source code and repositories. By using the Service, you grant LexOculus a limited, temporary license to access and analyze your repository content solely for the purpose of generating compliance reports. Repository metadata (README, dependency manifests, file tree) is stored for up to 30 days to enable report regeneration, then automatically purged. Source code files are never stored. See our <a href="/legal/privacy" className="text-[#FF4F00] hover:underline">Privacy Policy</a> for the full retention schedule.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">5. Subscriptions and Payments</h2>
                <p>
                    Certain features ("Pro Plan") require a paid subscription. Payment processing is handled by third-party providers. Billing occurs in advance on a recurring basis (monthly or annually).
                </p>
                <div className="bg-neutral-100 p-4 border-l-4 border-neutral-500">
                    <strong>Payment Processing:</strong> Payments are processed by our Merchant of Record, <strong>DodoPayments</strong>. By making a purchase, you agree to DodoPayments' terms and conditions in addition to these Terms.
                </div>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">6. Right of Withdrawal and Refunds (EU Consumers)</h2>
                <p>
                    Under the EU Consumer Rights Directive (2011/83/EU), you have the right to withdraw from a distance contract within <strong>14 days</strong> without giving any reason.
                </p>
                <p>
                    <strong>However</strong>, by proceeding to use the Service immediately upon subscription, you:
                </p>
                <ol className="list-decimal pl-5 space-y-2">
                    <li><strong>Expressly consent</strong> to LexOculus beginning performance of the digital service immediately.</li>
                    <li><strong>Acknowledge</strong> that you thereby <strong>waive your 14-day right of withdrawal</strong> once service delivery has begun.</li>
                </ol>
                <p>
                    If you do not wish to waive this right, you may request that access to paid features be delayed until the 14-day period has passed. Contact: <a href="mailto:founder@lexoculus.com" className="text-blue-600 hover:underline">founder@lexoculus.com</a>.
                </p>
                <p>
                    <strong>Termination:</strong> In accordance with the EU Data Act (Regulation (EU) 2023/2854), you may terminate your subscription at any time. The termination will take effect at the end of the current billing cycle.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">7. Limitation of Liability</h2>
                <p>
                    To the maximum extent permitted by applicable law, LexOculus shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or reputation, arising from your use of the Service. LexOculus is specifically not liable for any regulatory fines, penalties, or enforcement actions taken by any authority based on your reliance on its reports.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">8. Changes to Terms</h2>
                <p>
                    We may update these Terms from time to time. We will notify registered users of significant changes via email. Continued use after changes constitutes acceptance.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-2xl font-bold uppercase">9. Contact</h2>
                <p>
                    For any questions regarding these Terms, contact: <a href="mailto:founder@lexoculus.com" className="text-blue-600 hover:underline">founder@lexoculus.com</a>
                </p>
            </section>
        </div>
    );
}
