import { createServerClient } from '@/lib/infra/supabase-server';
import { prisma } from '@/lib/infra/prisma';
import { NextResponse } from 'next/server';
import { generateComplianceReport } from '@/lib/output/pdf-generator';

export async function GET(request: Request) {
    try {
        const supabase = await createServerClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
            return new NextResponse('Unauthorized', { status: 401 });
        }

        const firmMember = await prisma.firmMember.findUnique({
            where: { user_id: user.id },
            include: { firm: true }
        });

        if (!firmMember) {
            return new NextResponse('User is not associated with a firm', { status: 403 });
        }

        // Generate dummy data for the preview report
        const dummyData = {
            firm_branded: true,
            firm_name: firmMember.firm.name,
            firm_custom_intro: firmMember.firm.custom_intro || `This is a sample compliance report generated by ${firmMember.firm.name} to demonstrate our EU AI Act auditing capabilities.`,
            repo: {
                repo_name: 'sample-ai-application',
                repo_owner: 'acme-corp'
            },
            assessment: {
                final_risk_score: 85,
                final_risk_classification: 'HIGH_RISK',
                final_narrative: 'This simulated assessment indicates high risk due to the presence of biometric identification capabilities and automated decision-making processes. Robust human oversight mechanisms must be implemented before deployment.',
                final_matched_articles: [
                    {
                        article: 'Article 6(1) - High-Risk AI Systems',
                        category: 'Biometric Identification',
                        riskTier: 'HIGH_RISK',
                        reasoning: 'System processes biometric data for remote identification.',
                        requirements: ['Establish risk management system', 'Ensure human oversight', 'Keep detailed logs']
                    }
                ],
                context_summary: {
                    intended_use: 'Employee Access Control',
                    target_users: 'Internal Staff',
                    has_human_oversight: true,
                    has_data_safeguards: true
                },
                evidence_items: [
                    {
                        category: 'System Architecture',
                        description: 'Facial recognition module detected in authentication flow.',
                        supports_classification: 'HIGH',
                        confidence: '99%'
                    }
                ],
                compliance_readiness: {
                    overall_readiness: 'Partial. Key technical requirements are met, but documentation and formal risk management procedures are missing.',
                    developer_action_items: [
                        'Draft formal technical documentation compliant with Annex IV',
                        'Implement detailed logging for biometric processing events'
                    ]
                }
            },
            preliminary: {
                risk_narrative: 'Preliminary scan detected high-risk indicators associated with biometric processing.',
                evidence: [
                    {
                        name: 'face_recognition_v2',
                        severity: 'HIGH',
                        source_file: 'auth/biometrics.py',
                        type: 'Library',
                        version: '2.1.0',
                        triggered_articles: ['Article 6'],
                        risk_indicators: ['BIOMETRIC_PROCESSING', 'REMOTE_IDENTIFICATION']
                    }
                ],
                key_findings: [
                    'Dependency on external facial recognition API',
                    'Lack of clear opt-out mechanism in the frontend flow'
                ]
            },
            capabilities: {
                capabilities: [
                    'Facial Recognition',
                    'Biometric Data Processing',
                    'Automated Access Decision'
                ]
            }
        };

        const pdfBuffer = await generateComplianceReport(dummyData);

        return new NextResponse(new Uint8Array(pdfBuffer), {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `inline; filename="preview-report-${firmMember.firm.name.replace(/\s+/g, '-')}.pdf"`,
            },
        });
    } catch (error) {
        console.error('Error generating preview report:', error);
        return new NextResponse('Internal Server Error', { status: 500 });
    }
}
