'use server';

import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase-server';
import prisma from '@/lib/prisma';

interface RouteContext {
    params: Promise<{ id: string }>;
}

/**
 * POST /api/documents/:id/export
 * Export document to PDF
 * 
 * MRR HOOK: Requires active subscription
 */
export async function POST(request: NextRequest, context: RouteContext) {
    try {
        const { id } = await context.params;

        const supabase = await createServerClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        // Get document with AI system and user subscription
        const document = await prisma.complianceDocument.findUnique({
            where: { id },
            include: {
                ai_system: {
                    include: {
                        user: {
                            include: {
                                subscription: true
                            }
                        }
                    }
                }
            }
        });

        if (!document) {
            return NextResponse.json({ error: 'Document not found' }, { status: 404 });
        }

        if (document.ai_system.user_id !== user.id) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        // MRR GATING: Check subscription
        const subscription = document.ai_system.user?.subscription;
        const hasActiveSubscription = subscription?.status === 'active' ||
            subscription?.status === 'trialing';

        if (!hasActiveSubscription) {
            return NextResponse.json(
                { error: 'Active subscription required to export PDF' },
                { status: 403 }
            );
        }

        // Get markdown content
        const content = (document.content as { markdown?: string })?.markdown || '';

        // Generate HTML for PDF
        const html = generatePdfHtml(document.title, content, document.ai_system.name);

        // Convert to PDF using simple HTML approach
        // In production, you'd use a proper PDF library like puppeteer or pdfkit
        // For now, we return an HTML file that can be printed to PDF

        const pdfHtml = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${document.title}</title>
    <style>
        @page { margin: 2cm; }
        body { 
            font-family: 'Times New Roman', serif; 
            line-height: 1.6; 
            max-width: 21cm;
            margin: 0 auto;
            padding: 2cm;
        }
        h1 { font-size: 24pt; border-bottom: 2px solid #000; padding-bottom: 10px; }
        h2 { font-size: 18pt; margin-top: 20pt; }
        h3 { font-size: 14pt; margin-top: 16pt; }
        h4 { font-size: 12pt; }
        table { border-collapse: collapse; width: 100%; margin: 10pt 0; }
        th, td { border: 1px solid #333; padding: 8pt; text-align: left; }
        th { background: #f5f5f5; }
        .missing { background: #fff3cd; color: #856404; padding: 2px 4px; border-radius: 3px; }
        .header { text-align: center; margin-bottom: 20pt; }
        .footer { 
            text-align: center; 
            font-size: 10pt; 
            color: #666; 
            margin-top: 40pt; 
            padding-top: 10pt;
            border-top: 1px solid #ccc;
        }
        .meta { font-size: 10pt; color: #666; margin-bottom: 20pt; }
        hr { border: none; border-top: 1px solid #ccc; margin: 20pt 0; }
    </style>
</head>
<body>
    <div class="header">
        <img src="data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40"><rect width="40" height="40" fill="%23000"/><text x="20" y="28" text-anchor="middle" fill="%23fff" font-family="serif" font-size="20">L</text></svg>')}" alt="LexOculus" style="width: 40px; height: 40px;">
        <h1>${escapeHtml(document.title)}</h1>
        <div class="meta">
            AI System: ${escapeHtml(document.ai_system.name)}<br>
            Generated: ${new Date().toLocaleDateString()}<br>
            Version: ${document.version}
        </div>
    </div>
    ${markdownToHtml(content)}
    <div class="footer">
        <p>Generated by LexOculus EU AI Act Compliance Platform</p>
        <p>Document ID: ${document.id}</p>
        <p>Export Date: ${new Date().toISOString()}</p>
    </div>
</body>
</html>`;

        // Mark document as exported
        await prisma.complianceDocument.update({
            where: { id },
            data: { status: 'exported' }
        });

        console.log(`📄 [EXPORT] PDF exported for ${document.title}`);

        // Return as HTML (browser can Print to PDF)
        // In production, integrate with pdf-lib or puppeteer
        return new NextResponse(pdfHtml, {
            headers: {
                'Content-Type': 'text/html',
                'Content-Disposition': `attachment; filename="${document.document_type}-${document.ai_system.name.replace(/\s+/g, '-')}.html"`,
            }
        });

    } catch (error) {
        console.error('PDF export error:', error);
        return NextResponse.json(
            { error: 'Failed to export PDF' },
            { status: 500 }
        );
    }
}

function escapeHtml(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function generatePdfHtml(title: string, content: string, systemName: string): string {
    return content;
}

/**
 * Simple markdown to HTML converter
 */
function markdownToHtml(markdown: string): string {
    let html = markdown
        // Headers
        .replace(/^### (.*$)/gm, '<h3>$1</h3>')
        .replace(/^## (.*$)/gm, '<h2>$1</h2>')
        .replace(/^# (.*$)/gm, '<h1>$1</h1>')
        // Bold
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        // Italic
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
        // Code
        .replace(/`(.*?)`/g, '<code>$1</code>')
        // Horizontal rule
        .replace(/^---$/gm, '<hr>')
        // Lists
        .replace(/^- (.*$)/gm, '<li>$1</li>')
        // MISSING placeholders
        .replace(/\{\{MISSING:\s*([^}]+)\}\}/g, '<span class="missing">⚠️ MISSING: $1</span>')
        // Paragraphs
        .replace(/\n\n/g, '</p><p>')
        // Line breaks
        .replace(/\n/g, '<br>');

    // Wrap in paragraphs
    html = '<p>' + html + '</p>';

    // Fix list items (wrap consecutive li in ul)
    html = html.replace(/(<li>.*<\/li>)+/g, '<ul>$&</ul>');

    // Simple table handling
    html = html.replace(/\|([^|]+)\|([^|]+)\|/g, '<tr><td>$1</td><td>$2</td></tr>');

    return html;
}
